
`timescale 1 ns / 1 ps

	module ProtectionUnit_v1_0_wrapper #
	(
		// Users to add parameters here

		// User parameters ends
		// Do not modify the parameters beyond this line


		// Parameters of Axi Slave Bus Interface AXI_CONFIG
		parameter integer AXI_CONFIG_DATA_WIDTH	= 32,
		parameter integer AXI_CONFIG_ADDR_WIDTH	= 8,

		// Parameters of Axi Pass Through AXI_PT
		parameter  AXI_PT_TARGET_SLAVE_BASE_ADDR	= 32'h40000000,
		parameter integer AXI_PT_BURST_LEN	= 16,
		parameter integer AXI_PT_ID_WIDTH	= 1,
		parameter integer AXI_PT_DATA_WIDTH	= 32,
		parameter integer AXI_PT_ADDR_WIDTH	= 6,
		parameter integer AXI_PT_AWUSER_WIDTH	= 0,
		parameter integer AXI_PT_ARUSER_WIDTH	= 0,
		parameter integer AXI_PT_WUSER_WIDTH	= 0,
		parameter integer AXI_PT_RUSER_WIDTH	= 0,
		parameter integer AXI_PT_BUSER_WIDTH	= 0
	)
	(
		input wire  aclk,
		input wire  aresetn,

		// Ports of Axi Slave Bus Interface AXI_CONFIG
		input wire [AXI_CONFIG_ADDR_WIDTH-1 : 0] AXI_CONFIG_awaddr,
		input wire [2 : 0] AXI_CONFIG_awprot,
		input wire  AXI_CONFIG_awvalid,
		output wire  AXI_CONFIG_awready,
		input wire [AXI_CONFIG_DATA_WIDTH-1 : 0] AXI_CONFIG_wdata,
		input wire [(AXI_CONFIG_DATA_WIDTH/8)-1 : 0] AXI_CONFIG_wstrb,
		input wire  AXI_CONFIG_wvalid,
		output wire  AXI_CONFIG_wready,
		output wire [1 : 0] AXI_CONFIG_bresp,
		output wire  AXI_CONFIG_bvalid,
		input wire  AXI_CONFIG_bready,
		input wire [AXI_CONFIG_ADDR_WIDTH-1 : 0] AXI_CONFIG_araddr,
		input wire [2 : 0] AXI_CONFIG_arprot,
		input wire  AXI_CONFIG_arvalid,
		output wire  AXI_CONFIG_arready,
		output wire [AXI_CONFIG_DATA_WIDTH-1 : 0] AXI_CONFIG_rdata,
		output wire [1 : 0] AXI_CONFIG_rresp,
		output wire  AXI_CONFIG_rvalid,
		input wire  AXI_CONFIG_rready,

		// Ports of Axi Slave Bus Interface S_AXI_PT
		input wire [AXI_PT_ID_WIDTH-1 : 0] S_AXI_PT_awid,
		input wire [AXI_PT_ADDR_WIDTH-1 : 0] S_AXI_PT_awaddr,
		input wire [7 : 0] S_AXI_PT_awlen,
		input wire [2 : 0] S_AXI_PT_awsize,
		input wire [1 : 0] S_AXI_PT_awburst,
		input wire  S_AXI_PT_awlock,
		input wire [3 : 0] S_AXI_PT_awcache,
		input wire [2 : 0] S_AXI_PT_awprot,
		input wire [3 : 0] S_AXI_PT_awqos,
		input wire [3 : 0] S_AXI_PT_awregion,
		input wire [AXI_PT_AWUSER_WIDTH-1 : 0] S_AXI_PT_awuser,
		input wire  S_AXI_PT_awvalid,
		output wire  S_AXI_PT_awready,
		input wire [AXI_PT_DATA_WIDTH-1 : 0] S_AXI_PT_wdata,
		input wire [(AXI_PT_DATA_WIDTH/8)-1 : 0] S_AXI_PT_wstrb,
		input wire  S_AXI_PT_wlast,
		input wire [AXI_PT_WUSER_WIDTH-1 : 0] S_AXI_PT_wuser,
		input wire  S_AXI_PT_wvalid,
		output wire  S_AXI_PT_wready,
		output wire [AXI_PT_ID_WIDTH-1 : 0] S_AXI_PT_bid,
		output wire [1 : 0] S_AXI_PT_bresp,
		output wire [AXI_PT_BUSER_WIDTH-1 : 0] S_AXI_PT_buser,
		output wire  S_AXI_PT_bvalid,
		input wire  S_AXI_PT_bready,
		input wire [AXI_PT_ID_WIDTH-1 : 0] S_AXI_PT_arid,
		input wire [AXI_PT_ADDR_WIDTH-1 : 0] S_AXI_PT_araddr,
		input wire [7 : 0] S_AXI_PT_arlen,
		input wire [2 : 0] S_AXI_PT_arsize,
		input wire [1 : 0] S_AXI_PT_arburst,
		input wire  S_AXI_PT_arlock,
		input wire [3 : 0] S_AXI_PT_arcache,
		input wire [2 : 0] S_AXI_PT_arprot,
		input wire [3 : 0] S_AXI_PT_arqos,
		input wire [3 : 0] S_AXI_PT_arregion,
		input wire [AXI_PT_ARUSER_WIDTH-1 : 0] S_AXI_PT_aruser,
		input wire  S_AXI_PT_arvalid,
		output wire  S_AXI_PT_arready,
		output wire [AXI_PT_ID_WIDTH-1 : 0] S_AXI_PT_rid,
		output wire [AXI_PT_DATA_WIDTH-1 : 0] S_AXI_PT_rdata,
		output wire [1 : 0] S_AXI_PT_rresp,
		output wire  S_AXI_PT_rlast,
		output wire [AXI_PT_RUSER_WIDTH-1 : 0] S_AXI_PT_ruser,
		output wire  S_AXI_PT_rvalid,
		input wire  S_AXI_PT_rready,

		// Ports of Axi Master Bus Interface M_AXI_PT
		output wire [AXI_PT_ID_WIDTH-1 : 0] M_AXI_PT_awid,
		output wire [AXI_PT_ADDR_WIDTH-1 : 0] M_AXI_PT_awaddr,
		output wire [7 : 0] M_AXI_PT_awlen,
		output wire [2 : 0] M_AXI_PT_awsize,
		output wire [1 : 0] M_AXI_PT_awburst,
		output wire  M_AXI_PT_awlock,
		output wire [3 : 0] M_AXI_PT_awcache,
		output wire [2 : 0] M_AXI_PT_awprot,
		output wire [3 : 0] M_AXI_PT_awqos,
		output wire [AXI_PT_AWUSER_WIDTH-1 : 0] M_AXI_PT_awuser,
		output wire  M_AXI_PT_awvalid,
		input wire  M_AXI_PT_awready,
		output wire [AXI_PT_DATA_WIDTH-1 : 0] M_AXI_PT_wdata,
		output wire [AXI_PT_DATA_WIDTH/8-1 : 0] M_AXI_PT_wstrb,
		output wire  M_AXI_PT_wlast,
		output wire [AXI_PT_WUSER_WIDTH-1 : 0] M_AXI_PT_wuser,
		output wire  M_AXI_PT_wvalid,
		input wire  M_AXI_PT_wready,
		input wire [AXI_PT_ID_WIDTH-1 : 0] M_AXI_PT_bid,
		input wire [1 : 0] M_AXI_PT_bresp,
		input wire [AXI_PT_BUSER_WIDTH-1 : 0] M_AXI_PT_buser,
		input wire  M_AXI_PT_bvalid,
		output wire  M_AXI_PT_bready,
		output wire [AXI_PT_ID_WIDTH-1 : 0] M_AXI_PT_arid,
		output wire [AXI_PT_ADDR_WIDTH-1 : 0] M_AXI_PT_araddr,
		output wire [7 : 0] M_AXI_PT_arlen,
		output wire [2 : 0] M_AXI_PT_arsize,
		output wire [1 : 0] M_AXI_PT_arburst,
		output wire  M_AXI_PT_arlock,
		output wire [3 : 0] M_AXI_PT_arcache,
		output wire [2 : 0] M_AXI_PT_arprot,
		output wire [3 : 0] M_AXI_PT_arqos,
		output wire [AXI_PT_ARUSER_WIDTH-1 : 0] M_AXI_PT_aruser,
		output wire  M_AXI_PT_arvalid,
		input wire  M_AXI_PT_arready,
		input wire [AXI_PT_ID_WIDTH-1 : 0] M_AXI_PT_rid,
		input wire [AXI_PT_DATA_WIDTH-1 : 0] M_AXI_PT_rdata,
		input wire [1 : 0] M_AXI_PT_rresp,
		input wire  M_AXI_PT_rlast,
		input wire [AXI_PT_RUSER_WIDTH-1 : 0] M_AXI_PT_ruser,
		input wire  M_AXI_PT_rvalid,
		output wire  M_AXI_PT_rready
	);

	// Instantiation of Verilog compatabile SystemVerilog module
  
	ProtectionUnit_v1_0_verilog #(
		.AXI_CONFIG_DATA_WIDTH(AXI_CONFIG_DATA_WIDTH),
		.AXI_CONFIG_ADDR_WIDTH(AXI_CONFIG_ADDR_WIDTH),
		.AXI_PT_ID_WIDTH(AXI_PT_ID_WIDTH),
		.AXI_PT_DATA_WIDTH(AXI_PT_DATA_WIDTH),
		.AXI_PT_ADDR_WIDTH(AXI_PT_ADDR_WIDTH),
		.AXI_PT_AWUSER_WIDTH(AXI_PT_AWUSER_WIDTH),
		.AXI_PT_ARUSER_WIDTH(AXI_PT_ARUSER_WIDTH),
		.AXI_PT_WUSER_WIDTH(AXI_PT_WUSER_WIDTH),
		.AXI_PT_RUSER_WIDTH(AXI_PT_RUSER_WIDTH),
		.AXI_PT_BUSER_WIDTH(AXI_PT_BUSER_WIDTH),
		.AXI_PT_TARGET_SLAVE_BASE_ADDR(AXI_PT_TARGET_SLAVE_BASE_ADDR),
		.AXI_PT_BURST_LEN(AXI_PT_BURST_LEN)

	) ProtectionUnit_v1_0_verilog_inst (
		.aclk(aclk),
		.aresetn(aresetn),
		.AXI_CONFIG_awaddr(AXI_CONFIG_awaddr),
		.AXI_CONFIG_awprot(AXI_CONFIG_awprot),
		.AXI_CONFIG_awvalid(AXI_CONFIG_awvalid),
		.AXI_CONFIG_awready(AXI_CONFIG_awready),
		.AXI_CONFIG_wdata(AXI_CONFIG_wdata),
		.AXI_CONFIG_wstrb(AXI_CONFIG_wstrb),
		.AXI_CONFIG_wvalid(AXI_CONFIG_wvalid),
		.AXI_CONFIG_wready(AXI_CONFIG_wready),
		.AXI_CONFIG_bresp(AXI_CONFIG_bresp),
		.AXI_CONFIG_bvalid(AXI_CONFIG_bvalid),
		.AXI_CONFIG_bready(AXI_CONFIG_bready),
		.AXI_CONFIG_araddr(AXI_CONFIG_araddr),
		.AXI_CONFIG_arprot(AXI_CONFIG_arprot),
		.AXI_CONFIG_arvalid(AXI_CONFIG_arvalid),
		.AXI_CONFIG_arready(AXI_CONFIG_arready),
		.AXI_CONFIG_rdata(AXI_CONFIG_rdata),
		.AXI_CONFIG_rresp(AXI_CONFIG_rresp),
		.AXI_CONFIG_rvalid(AXI_CONFIG_rvalid),
		.AXI_CONFIG_rready(AXI_CONFIG_rready),
		.S_AXI_PT_awid(S_AXI_PT_awid),
		.S_AXI_PT_awaddr(S_AXI_PT_awaddr),
		.S_AXI_PT_awlen(S_AXI_PT_awlen),
		.S_AXI_PT_awsize(S_AXI_PT_awsize),
		.S_AXI_PT_awburst(S_AXI_PT_awburst),
		.S_AXI_PT_awlock(S_AXI_PT_awlock),
		.S_AXI_PT_awcache(S_AXI_PT_awcache),
		.S_AXI_PT_awprot(S_AXI_PT_awprot),
		.S_AXI_PT_awqos(S_AXI_PT_awqos),
		.S_AXI_PT_awregion(S_AXI_PT_awregion),
		.S_AXI_PT_awuser(S_AXI_PT_awuser),
		.S_AXI_PT_awvalid(S_AXI_PT_awvalid),
		.S_AXI_PT_awready(S_AXI_PT_awready),
		.S_AXI_PT_wdata(S_AXI_PT_wdata),
		.S_AXI_PT_wstrb(S_AXI_PT_wstrb),
		.S_AXI_PT_wlast(S_AXI_PT_wlast),
		.S_AXI_PT_wuser(S_AXI_PT_wuser),
		.S_AXI_PT_wvalid(S_AXI_PT_wvalid),
		.S_AXI_PT_wready(S_AXI_PT_wready),
		.S_AXI_PT_bid(S_AXI_PT_bid),
		.S_AXI_PT_bresp(S_AXI_PT_bresp),
		.S_AXI_PT_buser(S_AXI_PT_buser),
		.S_AXI_PT_bvalid(S_AXI_PT_bvalid),
		.S_AXI_PT_bready(S_AXI_PT_bready),
		.S_AXI_PT_arid(S_AXI_PT_arid),
		.S_AXI_PT_araddr(S_AXI_PT_araddr),
		.S_AXI_PT_arlen(S_AXI_PT_arlen),
		.S_AXI_PT_arsize(S_AXI_PT_arsize),
		.S_AXI_PT_arburst(S_AXI_PT_arburst),
		.S_AXI_PT_arlock(S_AXI_PT_arlock),
		.S_AXI_PT_arcache(S_AXI_PT_arcache),
		.S_AXI_PT_arprot(S_AXI_PT_arprot),
		.S_AXI_PT_arqos(S_AXI_PT_arqos),
		.S_AXI_PT_arregion(S_AXI_PT_arregion),
		.S_AXI_PT_aruser(S_AXI_PT_aruser),
		.S_AXI_PT_arvalid(S_AXI_PT_arvalid),
		.S_AXI_PT_arready(S_AXI_PT_arready),
		.S_AXI_PT_rid(S_AXI_PT_rid),
		.S_AXI_PT_rdata(S_AXI_PT_rdata),
		.S_AXI_PT_rresp(S_AXI_PT_rresp),
		.S_AXI_PT_rlast(S_AXI_PT_rlast),
		.S_AXI_PT_ruser(S_AXI_PT_ruser),
		.S_AXI_PT_rvalid(S_AXI_PT_rvalid),
		.S_AXI_PT_rready(S_AXI_PT_rready),
		.M_AXI_PT_awid(M_AXI_PT_awid),
		.M_AXI_PT_awaddr(M_AXI_PT_awaddr),
		.M_AXI_PT_awlen(M_AXI_PT_awlen),
		.M_AXI_PT_awsize(M_AXI_PT_awsize),
		.M_AXI_PT_awburst(M_AXI_PT_awburst),
		.M_AXI_PT_awlock(M_AXI_PT_awlock),
		.M_AXI_PT_awcache(M_AXI_PT_awcache),
		.M_AXI_PT_awprot(M_AXI_PT_awprot),
		.M_AXI_PT_awqos(M_AXI_PT_awqos),
		.M_AXI_PT_awuser(M_AXI_PT_awuser),
		.M_AXI_PT_awvalid(M_AXI_PT_awvalid),
		.M_AXI_PT_awready(M_AXI_PT_awready),
		.M_AXI_PT_wdata(M_AXI_PT_wdata),
		.M_AXI_PT_wstrb(M_AXI_PT_wstrb),
		.M_AXI_PT_wlast(M_AXI_PT_wlast),
		.M_AXI_PT_wuser(M_AXI_PT_wuser),
		.M_AXI_PT_wvalid(M_AXI_PT_wvalid),
		.M_AXI_PT_wready(M_AXI_PT_wready),
		.M_AXI_PT_bid(M_AXI_PT_bid),
		.M_AXI_PT_bresp(M_AXI_PT_bresp),
		.M_AXI_PT_buser(M_AXI_PT_buser),
		.M_AXI_PT_bvalid(M_AXI_PT_bvalid),
		.M_AXI_PT_bready(M_AXI_PT_bready),
		.M_AXI_PT_arid(M_AXI_PT_arid),
		.M_AXI_PT_araddr(M_AXI_PT_araddr),
		.M_AXI_PT_arlen(M_AXI_PT_arlen),
		.M_AXI_PT_arsize(M_AXI_PT_arsize),
		.M_AXI_PT_arburst(M_AXI_PT_arburst),
		.M_AXI_PT_arlock(M_AXI_PT_arlock),
		.M_AXI_PT_arcache(M_AXI_PT_arcache),
		.M_AXI_PT_arprot(M_AXI_PT_arprot),
		.M_AXI_PT_arqos(M_AXI_PT_arqos),
		.M_AXI_PT_aruser(M_AXI_PT_aruser),
		.M_AXI_PT_arvalid(M_AXI_PT_arvalid),
		.M_AXI_PT_arready(M_AXI_PT_arready),
		.M_AXI_PT_rid(M_AXI_PT_rid),
		.M_AXI_PT_rdata(M_AXI_PT_rdata),
		.M_AXI_PT_rresp(M_AXI_PT_rresp),
		.M_AXI_PT_rlast(M_AXI_PT_rlast),
		.M_AXI_PT_ruser(M_AXI_PT_ruser),
		.M_AXI_PT_rvalid(M_AXI_PT_rvalid),
		.M_AXI_PT_rready(M_AXI_PT_rready)
	);

	endmodule
